baseurl = "http://dataops.info/"
title = "DataOps"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-gb"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  description = "A site sharing DataOps resources from across the web"
  copyright = "&copy;2017 Locke Data Ltd"
  sidebarAbout = [
    "DevOps meets data",
    "A website dedicated to sharing DataOps resources"
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "steph@itsalocke.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [[params.navlinksexternal]]
  name = "Add a resource"
  url = "https://github.com/stephlocke/dataops#add-a-resource"

  [params.social]
  facebook      = "https://www.facebook.com/search/top/?q=dataops"
  twitter       = "https://twitter.com/search?q=%23dataops&src=typd"
  linkedin      = "https://www.linkedin.com/search/results/index/?keywords=dataops"
  github        = "https://github.com/stephlocke/dataops"